(function(){
"use strict";
const $=MathSphere.$,cfg=window.MathSphereConfig,q=$("#aiQuestion"),btn=$("#solveWithAI"),out=$("#aiSolution");if(!q||!btn||!out)return;
function normalize(text){let s=String(text||'');s=s.replace(/\\\\/g,'\\');s=s.replace(/```(?:markdown|latex|text)?/gi,'').replace(/```/g,'');return s.trim()}
function renderAnswer(text){let a=normalize(text);const tokens=[];a=a.replace(/\\\[(.*?)\\\]/gs,(_,m)=>{const id=tokens.length;tokens.push(`<div class="math-display">\\[${m.trim()}\\]</div>`);return `@@M${id}@@`}).replace(/\\\((.*?)\\\)/gs,(_,m)=>{const id=tokens.length;tokens.push(`<span class="math-inline">\\(${m.trim()}\\)</span>`);return `@@M${id}@@`});a=MathSphere.escape(a).replace(/^###\s+(.+)$/gm,'<h4>$1</h4>').replace(/^##\s+(.+)$/gm,'<h3>$1</h3>').replace(/^#\s+(.+)$/gm,'<h3>$1</h3>').replace(/\*\*(.*?)\*\*/gs,'<strong>$1</strong>').replace(/^Question\s*$/gim,'<div class="solution-heading">Question</div>').replace(/^Given:?\s*$/gim,'<div class="solution-heading">Given</div>').replace(/^Solution\s*$/gim,'<div class="solution-heading">Solution</div>').replace(/^Final Answer:?\s*$/gim,'<div class="final-answer-title">Final Answer</div>').replace(/^(Step\s+\d+(?:\s*:\s*.*)?)$/gim,'<div class="solution-step-title">$1</div>');a=a.replace(/\n{3,}/g,'\n\n').split(/\n\n+/).map(block=>block.trim()?`<p>${block.replace(/\n/g,'<br>')}</p>`:'').join('');tokens.forEach((v,i)=>{a=a.replace(`@@M${i}@@`,v)});return `<div class="ai-solution-content">${a}</div>`}
async function typeset(){if(window.MathJax?.typesetClear)window.MathJax.typesetClear([out]);if(window.MathJax?.typesetPromise)await MathJax.typesetPromise([out])}
const prompt=`You are MathSphere AI, an expert mathematics teacher for classes 9-12. Solve accurately, show complete working, and verify the final result in the original equation. Never output HTML or code fences. Use exactly one backslash in LaTeX commands. Use \\( ... \\) for inline mathematics and \\[ ... \\] for display mathematics. Never output double-backslash delimiters. Never write $$ delimiters. Do not replace square root with words such as sqr or sqrt outside LaTeX. Use \sqrt{x} inside LaTeX. Use clear textbook headings when appropriate.`;
async function solve(){const text=normalize(q.value);if(!text)return MathSphere.toast('Enter a mathematics question first.');if(!cfg.geminiApiKey||cfg.geminiApiKey.includes('PASTE_YOUR')){out.innerHTML='<div class="error-state">Gemini API key is not configured. Add it in <code>js/config.js</code>.</div>';return}btn.disabled=true;btn.textContent='Solving…';out.innerHTML='<div class="loading-state">MathSphere AI is solving…</div>';try{const url=cfg.geminiEndpoint+cfg.geminiModel+':generateContent?key='+encodeURIComponent(cfg.geminiApiKey);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({system_instruction:{parts:[{text:prompt}]},contents:[{role:'user',parts:[{text}]}],generationConfig:{temperature:.08,maxOutputTokens:5000}})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`Gemini returned ${r.status}`);const answer=d?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n')||'';if(!answer)throw Error('AI did not return a solution.');out.innerHTML=renderAnswer(answer);await typeset();out.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){out.innerHTML='<div class="error-state">'+MathSphere.escape(e.message)+'</div>'}finally{btn.disabled=false;btn.textContent='Solve with AI'}}
btn.addEventListener('click',solve);q.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')solve()});
})();