(function(){
"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];window.MathSphere=window.MathSphere||{};MathSphere.$=$;MathSphere.$$=$$;MathSphere.escape=v=>{const e=document.createElement('div');e.textContent=String(v??'');return e.innerHTML};MathSphere.toast=m=>{document.querySelector('.ms-toast')?.remove();const e=document.createElement('div');e.className='ms-toast';e.textContent=m;document.body.appendChild(e);setTimeout(()=>e.remove(),2400)};MathSphere.modal=(title,html)=>{const w=document.createElement('div');w.className='ms-modal-backdrop';w.innerHTML=`<div class="ms-modal" role="dialog" aria-modal="true"><button class="ms-modal-close" aria-label="Close">×</button><h3>${title}</h3><div>${html}</div></div>`;const close=()=>w.remove();w.addEventListener('click',e=>e.target===w&&close());w.querySelector('.ms-modal-close').addEventListener('click',close);document.body.appendChild(w)};
function setVisibility(h,visible){const t=$(h);if(!t)return;t.hidden=!visible;t.setAttribute('aria-hidden',String(!visible));if(visible)t.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',h)}
function nav(h){const t=$(h);if(!t)return; if(h==='#home'){hideSecondary();t.hidden=false;t.setAttribute('aria-hidden','false');t.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',h);return;} if(h==='#calculator'||h==='#syllabus')setVisibility(h,true); else {t.hidden=false;t.setAttribute('aria-hidden','false');t.scrollIntoView({behavior:'smooth',block:'start'});history.replaceState(null,'',h)} }
function hideSecondary(){['#calculator','#syllabus'].forEach(h=>{const t=$(h);if(t){t.hidden=true;t.setAttribute('aria-hidden','true')}})}
function addSectionControls(){
 $$('.page-section:not(#home)').forEach(sec=>{if(sec.querySelector('.section-hide-button'))return;const head=sec.querySelector('.section-heading');if(!head)return;const b=document.createElement('button');b.type='button';b.className='section-hide-button outline-button';b.textContent='Hide section';b.addEventListener('click',()=>{sec.hidden=true;sec.setAttribute('aria-hidden','true');MathSphere.toast('Section hidden. Open it again from the navigation.')});head.appendChild(b)})
}
$("#menuButton")?.addEventListener('click',()=>$("#mainNavigation")?.classList.toggle('is-open'));
$$("#mainNavigation a,.feature-link,.mobile-nav a").forEach(a=>a.addEventListener('click',e=>{const h=a.getAttribute('href');if(h?.startsWith('#')){e.preventDefault();$("#mainNavigation")?.classList.remove('is-open');nav(h)}}));
const si=$("#globalSearch");function search(){const q=(si?.value||'').trim().toLowerCase();if(!q)return MathSphere.toast('Type something to search.');const s=$$("main .page-section").find(x=>!x.hidden&&x.textContent.toLowerCase().includes(q))||$$("main .page-section").find(x=>x.textContent.toLowerCase().includes(q));if(!s)return MathSphere.toast('No matching content found.');s.hidden=false;nav('#'+s.id);s.classList.add('search-hit');setTimeout(()=>s.classList.remove('search-hit'),1600)}$("#searchButton")?.addEventListener('click',search);si?.addEventListener('keydown',e=>e.key==='Enter'&&search());
addSectionControls();hideSecondary();
})();
