(function(){
"use strict";
const $=MathSphere.$;let data,bank;
async function load(){[data,bank]=await Promise.all([fetch('data/curriculum.json').then(r=>r.json()),fetch('data/question-banks.json').then(r=>r.json())]);render()}
function relatedQuestions(board,c,title){return (bank?.[board]?.[c]?.mcqs||[]).filter(q=>String(q.topic||'').toLowerCase()===String(title).toLowerCase()).slice(0,4)}
function detailedNotes(t,b,c){const examples=relatedQuestions(b,c,t.title);return `<div class="note-body"><p><strong>What this topic covers:</strong> ${MathSphere.escape(t.summary)}</p><h4>Core learning points</h4><ul>${(t.key_points||[]).map(x=>`<li>${MathSphere.escape(x)}</li>`).join('')}</ul><h4>How to study this topic</h4><ol><li>Read the definition and notation carefully.</li><li>Write the main rule, property or method in your own words.</li><li>Follow one worked example step by step before attempting independent questions.</li><li>Check signs, units, domains, restrictions and the final result.</li><li>Finish with mixed board-style practice from the offline question bank.</li></ol><h4>Exam-focused practice</h4>${examples.length?`<div class="note-examples">${examples.map((q,i)=>`<div class="note-example"><strong>Example ${i+1}</strong><p>${MathSphere.escape(q.q)}</p></div>`).join('')}</div>`:'<p class="muted">Use the Full Book Practice bank for this topic.</p>'}<h4>Study tip</h4><p>${MathSphere.escape(t.study_tip)}</p><p class="muted">Board: ${b.toUpperCase()} • Class: ${c}</p></div>`}
function render(){const b=$("#syllabusBoard")?.value,c=$("#syllabusClass")?.value,o=$("#syllabusContent");if(!o)return;if(!b||!c){o.innerHTML='<div class="empty-state">Select board and class.</div>';return}const d=data[b][c];o.innerHTML=`<div class="source-row"><div><strong>Curriculum source</strong><small>${b.toUpperCase()} official curriculum page</small></div><a href="${d.source}" target="_blank" rel="noopener">Open official source</a></div><div class="topic-list">${d.topics.map((t,i)=>`<article class="topic-card"><span class="topic-number">${i+1}</span><h3>${MathSphere.escape(t.title)}</h3><p>${MathSphere.escape(t.summary)}</p><button class="topic-open" data-topic="${i}">Open detailed notes</button></article>`).join('')}</div>`;o.querySelectorAll('.topic-open').forEach(btn=>btn.onclick=()=>{const t=d.topics[Number(btn.dataset.topic)];MathSphere.modal(MathSphere.escape(t.title),detailedNotes(t,b,c))})}
$("#syllabusBoard")?.addEventListener('change',render);$("#syllabusClass")?.addEventListener('change',render);load().catch(()=>MathSphere.toast('Could not load local curriculum data.'));
})();
