(function(){
"use strict";
const $=MathSphere.$,cfg=window.MathSphereConfig;let bank=null;
async function init(){bank=await fetch("data/question-banks.json").then(r=>r.json());$("#startPractice")?.addEventListener("click",start);}
function shuffle(a){return [...a].sort(()=>Math.random()-0.5)}
function start(){
 const b=$("#practiceBoard").value,c=$("#practiceClass").value,type=$("#practiceType").value,nValue=$("#practiceCount").value,root=$("#practiceTest");
 if(!b||!c)return MathSphere.toast("Select board and class first.");
 const key=type==='mcq'?'mcqs':type;
 const source=(bank[b]?.[c]?.[key]||[]);if(!source.length)return MathSphere.toast("No questions are available for this selection.");
 const qs=nValue==='all'?shuffle(source):shuffle(source).slice(0,Math.min(Number(nValue),source.length));
 if(type==='mcq')renderMCQ(root,b,c,qs);else renderWritten(root,b,c,type,qs);
 root.scrollIntoView({behavior:'smooth',block:'start'});
}
function header(b,c,type,count){return `<div class="test-meta"><strong>${b.toUpperCase()} • Class ${c} • ${type==='mcq'?'MCQ Test':type==='short'?'Short Questions':'Long Questions'}</strong><span>${count} questions</span></div>`}
function renderMCQ(root,b,c,qs){
 root.innerHTML=`<form id="testForm">${header(b,c,'mcq',qs.length)}${qs.map((x,i)=>`<fieldset class="test-question"><legend><span class="q-number">${i+1}</span><span class="q-text">${MathSphere.escape(x.q)}</span></legend><div class="option-list">${(x.o||[]).map((z,j)=>`<label class="option-row"><input type="radio" name="q${i}" value="${j}"><span class="option-circle"></span><span class="option-letter">${String.fromCharCode(65+j)}</span><span class="option-text">${MathSphere.escape(z)}</span></label>`).join("")}</div></fieldset>`).join("")}<button class="primary-button submit-test" type="submit">Submit Test</button></form><div id="practiceResult"></div>`;
 $("#testForm",root).addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget);let score=0,answered=0;const wrong=[];qs.forEach((x,i)=>{const v=f.get("q"+i);if(v!==null)answered++;if(Number(v)===x.a)score++;else wrong.push({...x,userAnswer:v===null?"Not answered":x.o?.[Number(v)]});});const pct=qs.length?Math.round(score/qs.length*100):0;const weak=[...new Set(wrong.map(x=>x.topic).filter(Boolean))].slice(0,8);e.currentTarget.hidden=true;renderResult(root,{b,c,type:'mcq',qs,wrong,score,answered,pct,weak});});
}
function renderWritten(root,b,c,type,qs){
 root.innerHTML=`<form id="testForm">${header(b,c,type,qs.length)}${qs.map((x,i)=>`<fieldset class="test-question written-question"><legend><span class="q-number">${i+1}</span><span class="q-text">${MathSphere.escape(x.q)}</span></legend><textarea name="q${i}" rows="5" placeholder="Write your answer here…"></textarea></fieldset>`).join("")}<button class="primary-button submit-test" type="submit">Submit Test</button></form><div id="practiceResult"></div>`;
 $("#testForm",root).addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const answers=qs.map((x,i)=>({question:x.q,userAnswer:String(f.get('q'+i)||'').trim(),topic:x.topic||''}));const answered=answers.filter(x=>x.userAnswer).length;const pct=qs.length?Math.round(answered/qs.length*100):0;e.currentTarget.hidden=true;renderResult(root,{b,c,type,qs,answers,score:null,answered,pct,weak:[]});if(cfg.geminiApiKey&&!cfg.geminiApiKey.includes('PASTE_YOUR')&&answered){await evaluateWritten(root,b,c,type,answers);}});
}
function renderResult(root,state){
 const title=state.type==='mcq'?'MCQ Test Result':state.type==='short'?'Short Question Result':'Long Question Result';
 root.querySelector('#practiceResult').innerHTML=`<div class="result-banner"><h3>${title}</h3>${state.score!==null?`<p class="result-score">Score: <strong>${state.score}/${state.qs.length}</strong> (${state.pct}%)</p>`:''}<p>Answered: ${state.answered}/${state.qs.length}</p>${state.weak?.length?`<p><strong>Weak concepts:</strong> ${state.weak.map(MathSphere.escape).join(', ')}</p>`:''}<div class="result-actions">${state.weak?.length||state.wrong?.length?`<button id="studyWeakConcepts" class="primary-button" type="button">Study Weak Concepts with AI</button>`:''}<button id="restartPractice" class="outline-button" type="button">Start another test</button></div><div id="weakConceptResult"></div></div>`;
 root.querySelector('#restartPractice')?.addEventListener('click',()=>{root.innerHTML='';$("#startPractice")?.focus()});root.querySelector('#studyWeakConcepts')?.addEventListener('click',()=>studyWeak(root,state));root.querySelector('#practiceResult')?.scrollIntoView({behavior:'smooth',block:'nearest'});
}
async function evaluateWritten(root,b,c,type,answers){
 const box=root.querySelector('#practiceResult');box.querySelector('.result-banner')?.insertAdjacentHTML('beforeend','<div class="loading-state" id="aiEvaluationLoading">AI is checking your written answers…</div>');
 const prompt=`You are a strict but helpful mathematics teacher. Evaluate these ${type} answers for ${c} ${b.toUpperCase()} Mathematics. Return ONLY JSON: {"score":number,"total":number,"weakConcepts":[string],"feedback":[{"question":string,"correct":boolean,"feedback":string}]}. Do not give credit for blank answers. Identify concepts from the supplied topic or infer the exact concept from the question.\n${JSON.stringify(answers)}`;
 try{const url=cfg.geminiEndpoint+cfg.geminiModel+':generateContent?key='+encodeURIComponent(cfg.geminiApiKey);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.05,maxOutputTokens:5000,responseMimeType:'application/json'}})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`Gemini returned ${r.status}`);const raw=d.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('')||'';const result=JSON.parse(raw);box.querySelector('#aiEvaluationLoading')?.remove();box.querySelector('.result-banner')?.insertAdjacentHTML('afterbegin',`<p class="result-score">AI Score: <strong>${result.score}/${result.total}</strong></p>${result.weakConcepts?.length?`<p><strong>AI weak concepts:</strong> ${result.weakConcepts.map(MathSphere.escape).join(', ')}</p>`:''}`);box.dataset.weak=JSON.stringify(result.weakConcepts||[]);const btn=box.querySelector('#studyWeakConcepts');if(!btn&&result.weakConcepts?.length){box.querySelector('.result-actions')?.insertAdjacentHTML('afterbegin','<button id="studyWeakConcepts" class="primary-button" type="button">Study Weak Concepts with AI</button>');box.querySelector('#studyWeakConcepts')?.addEventListener('click',()=>studyWeak(root,{b,c,type,answers,weak:result.weakConcepts||[]}));}}
 catch(e){box.querySelector('#aiEvaluationLoading')?.remove();MathSphere.toast('AI evaluation could not be completed: '+e.message)}
}
async function studyWeak(root,state){
 const box=root.querySelector('#weakConceptResult');if(!box)return;box.innerHTML='<div class="loading-state">AI is preparing a focused lesson from your mistakes…</div>';if(!cfg.geminiApiKey||cfg.geminiApiKey.includes('PASTE_YOUR'))return box.innerHTML='<div class="error-state">Gemini API key is not configured.</div>';
 const wrong=state.wrong||[];const weak=state.weak||[];const prompt=`You are MathSphere AI tutor. Teach the student the weak mathematics concepts revealed by this test. Concepts: ${weak.join(', ')}. Wrong questions and answers: ${JSON.stringify(wrong)}. Give a short lesson for each concept, one worked example, then 2 practice questions without answers. Use clean LaTeX with \\(...\\) and \\[...\\]. Never use raw $$ or code fences.`;
 try{const url=cfg.geminiEndpoint+cfg.geminiModel+':generateContent?key='+encodeURIComponent(cfg.geminiApiKey);const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{temperature:.12,maxOutputTokens:6000}})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||`Gemini returned ${r.status}`);let text=d.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('\n')||'';text=text.replace(/\\\\/g,'\\');const token=[];text=text.replace(/\\\[(.*?)\\\]/gs,(_,m)=>{const i=token.length;token.push(`<div class="math-display">\\[${m.trim()}\\]</div>`);return `@@M${i}@@`}).replace(/\\\((.*?)\\\)/gs,(_,m)=>{const i=token.length;token.push(`<span class="math-inline">\\(${m.trim()}\\)</span>`);return `@@M${i}@@`});text=MathSphere.escape(text).replace(/\*\*(.*?)\*\*/gs,'<strong>$1</strong>').split(/\n\n+/).map(x=>x.trim()?`<p>${x.replace(/\n/g,'<br>')}</p>`:'').join('');token.forEach((v,i)=>text=text.replace(`@@M${i}@@`,v));box.innerHTML=`<div class="weak-concept-lesson"><h4>Personalized Weak-Concept Lesson</h4>${text}</div>`;if(window.MathJax?.typesetPromise)await MathJax.typesetPromise([box]);box.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(e){box.innerHTML='<div class="error-state">'+MathSphere.escape(e.message)+'</div>'}
}
init().catch(()=>MathSphere.toast("Question bank could not be loaded."));
})();
